# ClusterIP Service Definition
# This service exposes the nginx pod within the cluster
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
    version: blue  # Switch back to blue deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

apiVersion: v1
kind: Service
metadata:
  name: nginx-service-canary
spec:
  selector:
    app: nginx
    version: stable  # Initially route to stable version
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80