apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3                    # Run 3 replica pods
  selector:
    matchLabels:
      app: nginx
  template:                      # Pod template
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "250m"         # 0.25 CPU
            memory: "64Mi"
          limits:
            cpu: "500m"         # 0.5 CPU
            memory: "128Mi"