apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-health
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-health
  template:
    metadata:
      labels:
        app: nginx-health
    spec:
      containers:
      - name: nginx
        image: nginx:1.14
        ports:
        - containerPort: 80
        livenessProbe:          # Determines if the container is alive
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15  # Wait 15s before first probe
          periodSeconds: 10        # Check every 10s
          timeoutSeconds: 5        # Probe timeout after 5s
          failureThreshold: 3      # Fail after 3 consecutive failures
        readinessProbe:         # Determines if container is ready for traffic
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5   # Wait 5s before first probe
          periodSeconds: 5         # Check every 5s
          successThreshold: 1      # Mark ready after 1 success
          failureThreshold: 3      # Mark not ready after 3 failures