apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-probe-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-probe-test
  template:
    metadata:
      labels:
        app: nginx-probe-test
    spec:
      containers:
      - name: nginx
        image: nginx:1.14
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo 'Healthy' > /usr/share/nginx/html/health; sleep 30; rm /usr/share/nginx/html/health"]