apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-test
  template:
    metadata:
      labels:
        app: resource-test
    spec:
      containers:
      - name: stress
        image: polinux/stress
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        command: ["stress"]
        args: ["--cpu", "2", "--timeout", "60s"]