image:
  file: .gitpod.Dockerfile

features:
  docker-in-docker: true

tasks:
  - init: |
      dockerd-entrypoint.sh & sleep 10
      kind create cluster
    command: |
      kubectl cluster-info
      kubectl get nodes
