apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: games.gaming.example.com
spec:
  group: gaming.example.com
  names:
    kind: Game
    plural: games
    singular: game
    shortNames:
      - gm
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                gameName:
                  type: string
                  description: "Name of the game server (e.g. minecraft)"
                  enum:
                    - "minecraft"
                    - "terraria"
                    - "valheim"
                    - "factorio"
                gameVersion:
                  type: string
                  description: "Version of the game (semver)"
                  pattern: '^v?\d+\.\d+\.\d+$'
                serverName:
                  type: string
                  description: "Public name of the server"
                  minLength: 3
                  maxLength: 50
                  pattern: '^[a-zA-Z0-9][a-zA-Z0-9-_. ]+[a-zA-Z0-9]$'
                players:
                  type: integer
                  minimum: 1 
                  maximum: 100
                  description: "Maximum number of players"
                port:
                  type: integer
                  minimum: 1024
                  maximum: 65535
                  description: "Port the game server runs on"
                mode:
                  type: string
                  description: "Game mode"
                  enum:
                    - "survival"
                    - "creative"
                    - "adventure"
                difficulty:
                  type: string
                  description: "Game difficulty"
                  enum:
                    - "peaceful"
                    - "easy"
                    - "normal"
                    - "hard"
                  default: "normal"
              required:
                - gameName
                - players
                - port
                - serverName