apiVersion: example.com/v1
kind: WebApp
metadata:
  name: my-webapp
spec:
  image: nginx:1.14
  port: 80
  replicas: 3
  domains:
    - myapp.example.com
    - www.myapp.example.com
  ssl:
    enabled: true
    secretName: myapp-tls-secret
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"