# sleep.yaml
apiVersion: v1
kind: Pod
metadata:
  name: sleep
  labels:
    app: sleep
  annotations:
    sidecar.istio.io/inject: "true"
spec:
  containers:
  - name: sleep
    image: curlimages/curl:8.2.1
    command: ["/bin/sleep", "3650d"]
    securityContext:
      runAsUser: 1000
