apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    server {
      listen 80;
      server_name localhost;
      
      location / {
        auth_basic "Restricted Access";
        auth_basic_user_file /etc/nginx/auth/.htpasswd;
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
      }
    }
  custom-page.html: |
    <!DOCTYPE html>
    <html>
    <body>
      <h1>Welcome to Kubernetes ConfigMap Demo!</h1>
      <p>This page is served using a configuration from ConfigMap</p>
      <p>Access is protected by basic auth from our Secret</p>
    </body>
    </html>
  index.html: |
    <!DOCTYPE html>
    <html>
    <body>
      <h1>Hello from ConfigMap!</h1>
      <p>This content is loaded from a ConfigMap</p>
    </body>
    </html>